### ISSUE TITLE
设置好了怎么运行的

### ISSUE THREAD

**Issue by bingbaicai** [yanyaoli/daily60s#1]
已经按你的教程设置好了，他是每天的哪个时间段自动推送吗？

**Comment by yanyaoli** [comment]
每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Cron值。

**Comment by bingbaicai** [comment]
> 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。

![image](https://github.com/viiayil/daily60s/assets/66243694/8d083ccb-fed7-4f79-a446-200f6331bdc3)
是这里修改吗？老师

**Comment by viiayil** [comment]
是的，该时间为UTC标准时间，如需北京时间请注意转化。Sent using the mobile mail appOn 2023/8/7 at 14:20, bingbaicai wrote:
                
            
            
                
                    From: "bingbaicai" ***@***.***>Date: August 7, 2023To: "viiayil/daily60s" ***@***.***>Cc: "Comment" ***@***.***>,"orz" ***@***.***>Subject: Re: [viiayil/daily60s] 设置好了怎么运行的 (Issue #1)
                
                

每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。


是这里修改吗？老师

**Comment by yanyaoli** [comment]
> > 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。
> 
> 
> 
> ![image](https://github.com/viiayil/daily60s/assets/66243694/8d083ccb-fed7-4f79-a446-200f6331bdc3)
> 
> 是这里修改吗？老师

是的，该时间为UTC标准时间，如需北京时间请注意转化。

**Comment by bingbaicai** [comment]
谢谢 明白了

**Comment by bingbaicai** [comment]
> > > 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/66243694/258716102-8d083ccb-fed7-4f79-a446-200f6331bdc3.png)
> > 是这里修改吗？老师
> 
> 是的，该时间为UTC标准时间，如需北京时间请注意转化。

我设置了时间，没有推送。我按教程里面添加了环境变量了

**Comment by yanyaoli** [comment]
> > > > 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。
> 
> > > 
> 
> > > 
> 
> > > ![image](https://user-images.githubusercontent.com/66243694/258716102-8d083ccb-fed7-4f79-a446-200f6331bdc3.png)
> 
> > > 是这里修改吗？老师
> 
> > 
> 
> > 是的，该时间为UTC标准时间，如需北京时间请注意转化。
> 
> 
> 
> 我设置了时间，没有推送。我按教程里面添加了环境变量了

一般在设定时间后几分钟内推送，若未推送，请尝试在Action中手动运行，检查代码是否报错，或token无效。

**Comment by bingbaicai** [comment]
> > > > > 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > ![image](https://user-images.githubusercontent.com/66243694/258716102-8d083ccb-fed7-4f79-a446-200f6331bdc3.png)
> > 
> > 
> > > > 是这里修改吗？老师
> > 
> > 
> > > 
> > 
> > 
> > > 是的，该时间为UTC标准时间，如需北京时间请注意转化。
> > 
> > 
> > 我设置了时间，没有推送。我按教程里面添加了环境变量了
> 
> 一般在设定时间后几分钟内推送，若未推送，请尝试在Action中手动运行，检查代码是否报错，或token无效。

OK 了谢谢 是action里面All workflows才行

**Comment by bingbaicai** [comment]
> > > > > 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > ![image](https://user-images.githubusercontent.com/66243694/258716102-8d083ccb-fed7-4f79-a446-200f6331bdc3.png)
> > 
> > 
> > > > 是这里修改吗？老师
> > 
> > 
> > > 
> > 
> > 
> > > 是的，该时间为UTC标准时间，如需北京时间请注意转化。
> > 
> > 
> > 我设置了时间，没有推送。我按教程里面添加了环境变量了
> 
> 一般在设定时间后几分钟内推送，若未推送，请尝试在Action中手动运行，检查代码是否报错，或token无效。

早上还是没有推送。我手动他能推送。奇怪🤔️

**Comment by yanyaoli** [comment]
> > > > > > 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > ![image](https://user-images.githubusercontent.com/66243694/258716102-8d083ccb-fed7-4f79-a446-200f6331bdc3.png)
> 
> > > 
> 
> > > 
> 
> > > > > 是这里修改吗？老师
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 是的，该时间为UTC标准时间，如需北京时间请注意转化。
> 
> > > 
> 
> > > 
> 
> > > 我设置了时间，没有推送。我按教程里面添加了环境变量了
> 
> > 
> 
> > 一般在设定时间后几分钟内推送，若未推送，请尝试在Action中手动运行，检查代码是否报错，或token无效。
> 
> 
> 
> 早上还是没有推送。我手动他能推送。奇怪🤔️
自动运行能够成功，说明代码没有问题。GitHub Action推送失败一般会有邮件通知，如果没有通知，说明未运行（未到达设定的运行时间），麻烦检查一下设定的时间和Cron格式，UTC时间需要+8:00则为北京时间。

**Comment by bingbaicai** [comment]
> > > > > > > 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > ![image](https://user-images.githubusercontent.com/66243694/258716102-8d083ccb-fed7-4f79-a446-200f6331bdc3.png)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 是这里修改吗？老师
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 是的，该时间为UTC标准时间，如需北京时间请注意转化。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 我设置了时间，没有推送。我按教程里面添加了环境变量了
> > 
> > 
> > > 
> > 
> > 
> > > 一般在设定时间后几分钟内推送，若未推送，请尝试在Action中手动运行，检查代码是否报错，或token无效。
> > 
> > 
> > 早上还是没有推送。我手动他能推送。奇怪🤔️
> > 自动运行能够成功，说明代码没有问题。GitHub Action推送失败一般会有邮件通知，如果没有通知，说明未运行（未到达设定的运行时间），麻烦检查一下设定的时间和Cron格式，UTC时间需要+8:00则为北京时间。

推了推了^_^。不过这个延迟有点大，我设置的00:00，按道理他是北京时间8点推送，结果8:53才推送过来，我去把时间往前设置下 谢谢解答

**Comment by yanyaoli** [comment]
> > > > > > > > 每日推送时间默认设置为北京时间上午06:30，可根据自身需要在工作流文件中修改Corn值。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > ![image](https://user-images.githubusercontent.com/66243694/258716102-8d083ccb-fed7-4f79-a446-200f6331bdc3.png)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 是这里修改吗？老师
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 是的，该时间为UTC标准时间，如需北京时间请注意转化。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 我设置了时间，没有推送。我按教程里面添加了环境变量了
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 一般在设定时间后几分钟内推送，若未推送，请尝试在Action中手动运行，检查代码是否报错，或token无效。
> 
> > > 
> 
> > > 
> 
> > > 早上还是没有推送。我手动他能推送。奇怪🤔️
> 
> > > 自动运行能够成功，说明代码没有问题。GitHub Action推送失败一般会有邮件通知，如果没有通知，说明未运行（未到达设定的运行时间），麻烦检查一下设定的时间和Cron格式，UTC时间需要+8:00则为北京时间。
> 
> 
> 
> 推了推了^_^。不过这个延迟有点大，我设置的00:00，按道理他是北京时间8点推送，结果8:53才推送过来，我去把时间往前设置下 谢谢解答
可能该时间段Action服务太多，所以比较慢😂
